### ISSUE TITLE
!!MOD and !!CALLOUT should be toned down a bit

### ISSUE THREAD

**Issue by zapacni** [dfmeta/devforumplus#22]
While these shortcuts have good intentions they seem a bit too minimod-like, which is ironic considering the goal of them is to discourage minimodding.

**Comment by FxllenCode** [comment]
Good point. I'm open to changes, make it sound more friendly.

**Comment by FxllenCode** [comment]
Sorry for the delay- busy with finals and final grind on the re-release of my site. Will have this finished by Sunday.
