### ISSUE TITLE
coefficients is not flaired, other user is instead

### ISSUE THREAD

**Issue by zapacni** [dfmeta/devforumplus#26]
I was browsing a topic, and by coincidence I find a user named Tycoon_dev. Looks like this user is flaired instead of coefficients. no offense but i dont think this is intentional ;p

![image](https://user-images.githubusercontent.com/60857303/101982801-3f686a80-3c2b-11eb-8fbc-68c4805189b4.png)

**Comment by ElliottLMz** [comment]
coefficients id as per dfand code: 112950
tycoon dev's id: 22327

this should not be happening

**Comment by FxllenCode** [comment]
I believe that was fixed in a commit, it was not pushed to chrome store yet.

https://github.com/dfmeta/devforumplus/commit/5c738f9c34babcb792287de5912007ac669cd8b9
